[package]
name = "hermitdb"
version = "0.1.0"
authors = ["David Rusu <davidrusu@protonmail.com>"]
description = "A private decentralized database replicated over Git (or any other distributed log)"
license="GPL-2.0"
build = "build.rs"

[dependencies]
git2 = "0.7.1"
ring = "0.13.0-alpha"
serde = "1.0.70"
serde_derive = "1.0.70"
data-encoding = "2.1.1"
time = "0.1.39"
tempfile = "3.0.1"
assert_matches = "1.2.0"
sled = "0.15.17"

# [dependencies.sled]
# path = "../sled/crates/sled"

[dependencies.crdts]
version = "1.3.0"
path = "../rust-crdt"
# git = "https://github.com/davidrusu/rust-crdt"
# branch = "op-replication"

[dependencies.bincode]
version = "1.0.1"
features = ["i128"]

[dev-dependencies]
quickcheck = "0.6.2"
skeptic = "0.13"

[build-dependencies]
skeptic = "0.13"

