[package]
name = "gitdb"
version = "0.1.1"
authors = ["David Rusu <davidrusu@protonmail.com>"]
description = "A security concious database for apps that respect user privacy"
license="GPL-2.0"

[dependencies]
git2 = "0.7.1"
ring = "0.13.0-alpha"
serde = "1.0.70"
serde_derive = "1.0.70"
data-encoding = "2.1.1"
time = "0.1.39"
tempfile = "3.0.1"
assert_matches = "1.2.0"
sled = "0.15.17"

[dev-dependencies]
quickcheck = "0.6.2"

# [dependencies.sled]
# path = "../sled/crates/sled"

[dependencies.crdts]
git = "https://github.com/davidrusu/rust-crdt"
branch = "op-replication"

[dependencies.bincode]
version = "1.0.1"
features = ["i128"]
